name: app_version
description: This is a Flutter widget that displays the version status of apps and can easily guide user to update your app.
version: 0.0.1
homepage: https://github.com/myConsciousness/app-version

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  new_version: ^0.2.3
  package_info_plus: ^1.3.0
  universal_io: ^2.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  import_sorter: ^4.6.0
